In [1]:


%load_ext autoreload
%autoreload 2

In [6]:
import numpy as np

In [7]:
from baum_welch import *
from data_processing import *

In [2]:
import pandas as pd

### read in the data

In [19]:
data = pd.read_csv("data/sample_data.csv")

In [13]:
data["possession_id"] = data.groupby(["gameId","playId"]).ngroup()
data.sort_values(["nflId","nflId_pr","time"]).to_csv("data/sample_data.csv", index = False)

### fitted params

In [173]:
tau_hat = np.array([[0.51700617], 
 [0.48136962]] )
sigma_hat = 2.033743323394018 
rho_hat = 0.049970069818971584

In [178]:
weeks_df = []
for l in range(8):
    data = pd.read_csv(f"data/sample_data_week_{l}.csv")
    fitted_dict = {}
    pass_blocker_index_ids = {}
    pass_rusher_index_ids = {}
    for key, grouped_data in data.groupby("possession_id"):
        try:
            B, O, D = possession_to_voxel(grouped_data)
            j = D.shape[1]
            k = O.shape[1]
            starting_state_distribution = np.ones((j, k)) / k
            I,_,_ = expectation_matchup_possession(tau_hat, sigma_hat, rho_hat, starting_state_distribution, D, O, B )
            fitted_dict[key] = I
        except Exception as e:
            print(f"Error: {e} on example {key}")
    
    for key, grouped_data in data.groupby("possession_id"):
        pass_blocker_index_ids[key] = {}
        pass_rusher_index_ids[key] = {}
        for x, player_df in enumerate(grouped_data.groupby("nflId")):
            pass_blocker_index_ids[key][x] = player_df[0]
        for z, player_df in enumerate(grouped_data.groupby("nflId_pr")):
            pass_rusher_index_ids[key][z] = player_df[0]
    all_pos_df_list = []
    for possession in fitted_dict:
        pos_df_list = []
        assignments = fitted_dict[possession]
        pass_rusher_indexes = pass_rusher_index_ids[possession]
        pass_blocker_indexes = pass_blocker_index_ids[possession]
        for i in range(assignments.shape[0] - 1):
            cur_assignment = assignments[i,:,:]
            pos_df_raw = pd.DataFrame(cur_assignment, columns = pass_rusher_indexes.values(), index=pass_blocker_indexes.values()).rename_axis("nflId").reset_index().melt(id_vars=["nflId"], value_name = "prob_assigned", var_name = "nflId_pr")
            pos_df_raw["frame_id"] = i + 1
            pos_df_raw["possession_id"] = possession
            pos_df_list.append(pos_df_raw)
        all_pos_df_list.append(pd.concat(pos_df_list))
    final_assignment_df = pd.concat(all_pos_df_list)
    final_assignment_df["week"] = l + 1
    weeks_df.append(final_assignment_df)

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 58 and the array at index 1 has size 1 on example 670

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 31 and the array at index 1 has size 1 on example 272

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):
/var/folders/d4/h18vf05j4jsgmvd2j5k8nl840000gn/T/ipykernel_96464/2039532509.py:21: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for x, player_df in enumerate(grouped_data.groupby(["nflId"])):

In [179]:
len(weeks_df)

8

In [180]:
pd.concat(weeks_df).to_csv("assignment_data.csv",index = False)

In [181]:
assignment_data = pd.read_csv("assignment_data.csv")

8310285

In [48]:
assignments[0,:,:]

array([[0.01682958, 0.62238324, 0.16371947, 0.1970677 ],
       [0.69177259, 0.00187623, 0.0939913 , 0.21235988],
       [0.09265247, 0.31859786, 0.26557873, 0.32317093],
       [0.51595756, 0.01061189, 0.18978307, 0.28364747],
       [0.30894733, 0.05815617, 0.2899921 , 0.3429044 ]])

In [49]:
pass_rusher_indexes

{0: 35441.0, 1: 35454.0, 2: 38588.0, 3: 46081.0}

In [50]:
pass_blocker_indexes

{0: 37082.0, 1: 42654.0, 2: 46119.0, 3: 47873.0, 4: 52554.0}

In [55]:
final_assignment_df

      nflId nflId_pr  prob_assigned  frame_id  possession_id
0   40151.0  41263.0       0.089869         1              0
1   42377.0  41263.0       0.000470         1              0
2   42404.0  41263.0       0.006664         1              0
3   46163.0  41263.0       0.311584         1              0
4   52421.0  41263.0       0.552701         1              0
..      ...      ...            ...       ...            ...
37  46084.0  53460.0       0.329292        34           1174
38  47920.0  53460.0       0.581825        34           1174
39  48235.0  53460.0       0.536559        34           1174
40  52517.0  53460.0       0.514807        34           1174
41  53446.0  53460.0       0.635211        34           1174

[1114368 rows x 5 columns]

In [56]:
player_data = pd.read_csv("data/players.csv")

In [60]:
pb_merge = player_data.merge(final_assignment_df, left_on = ["nflId"], right_on = "nflId")[["nflId","officialPosition","displayName","nflId_pr", "prob_assigned","frame_id","possession_id"]]

In [65]:
pb_merge.rename(mapper = {"displayName":"pass_blocker_name", "officialPosition": "blocker_position"},inplace=True, axis= 1)

In [87]:
pb_merge_2 = pb_merge.merge(player_data, how = "inner", left_on = "nflId_pr", right_on = 'nflId')[["nflId_x","officialPosition","displayName","nflId_pr", "prob_assigned","frame_id","possession_id", "blocker_position","pass_blocker_name"]]

In [88]:
pb_merge_2.rename(mapper = {"displayName":"pass_rusher_name", "officialPosition": "rusher_position", "nflId_x":"nflId"},inplace=True, axis= 1)

In [95]:
attention_drawn_week_1 = pb_merge_2.groupby("nflId_pr").agg({"prob_assigned": np.mean, "pass_rusher_name": pd.unique}).reset_index().sort_values("prob_assigned", ascending = False).merge(player_data, right_on = "nflId", left_on = "nflId_pr")[["nflId_pr", "pass_rusher_name", "officialPosition", "prob_assigned"]]

In [100]:
attention_drawn_week_1.groupby("officialPosition").apply(lambda x: x.sort_values("prob_assigned", ascending = False).head(5))

                      nflId_pr        pass_rusher_name officialPosition  \
officialPosition
CB               220   43343.0   [Mackensie Alexander]               CB
                 233   53530.0      [Ifeatu Melifonwu]               CB
                 304   53565.0          [Marco Wilson]               CB
                 305   42816.0             [Troy Hill]               CB
                 332   52546.0        [L'Jarius Sneed]               CB
DE               2     53876.0       [Raymond Johnson]               DE
                 10    44944.0         [Deatrich Wise]               DE
                 21    44886.0         [Chris Wormley]               DE
                 22    53935.0          [Darius Hodge]               DE
                 26    35449.0          [Tyson Alualu]               DE
DT               5     53587.0         [Daviyon Nixon]               DT
                 6     38542.0          [Fletcher Cox]               DT
                 8     42497.0        [Tyeler Davison]               DT
                 11    52496.0        [Jordan Elliott]               DT
                 12    48544.0            [Shy Tuttle]               DT
FS               63    47899.0          [Amani Hooker]               FS
                 255   41502.0       [Daniel Sorensen]               FS
                 303   47882.0          [Mike Edwards]               FS
                 329   53674.0           [Tre Norwood]               FS
                 338   47915.0       [Ugochukwu Amadi]               FS
ILB              0     41348.0      [Anthony Hitchens]              ILB
                 1     43404.0    [De'Vondre Campbell]              ILB
                 15    44968.0           [Jayon Brown]              ILB
                 34    43062.0          [Nick Dzubnar]              ILB
                 61    46212.0      [Ja'Whaun Bentley]              ILB
MLB              111   37317.0         [Malcolm Smith]              MLB
                 171   46139.0           [Fred Warner]              MLB
                 194   46105.0     [Shaquille Leonard]              MLB
                 206   44974.0        [Anthony Walker]              MLB
                 213   43323.0          [Jaylon Smith]              MLB
NT               4     52464.0         [Raekwon Davis]               NT
                 7     44991.0        [Davon Godchaux]               NT
                 9     48198.0            [Bryan Mone]               NT
                 14    42559.0   [Christian Covington]               NT
                 31    40030.0          [John Jenkins]               NT
OLB              3     46088.0  [Leighton Vander Esch]              OLB
                 29    42467.0        [Kwon Alexander]              OLB
                 46    43516.0     [Stephen Weatherly]              OLB
                 70    53639.0       [Victor Dimukeje]              OLB
                 84    43333.0            [Jihad Ward]              OLB
SS               135   45021.0             [Rudy Ford]               SS
                 274   43350.0             [Vonn Bell]               SS
                 341   47892.0          [Khari Willis]               SS
                 344   44818.0           [Jamal Adams]               SS
                 345   44999.0           [Chuck Clark]               SS

                      prob_assigned
officialPosition
CB               220       0.218680
                 233       0.214377
                 304       0.191717
                 305       0.191120
                 332       0.178914
DE               2         0.387504
                 10        0.312592
                 21        0.299271
                 22        0.299042
                 26        0.296849
DT               5         0.317024
                 6         0.315628
                 8         0.313494
                 11        0.312052
                 12        0.310654
FS               63        0.274971
                 255       0.209012
                 303       0.192000
                 329       0.181553
                 338       0.173529
ILB              0         0.533141
                 1         0.425384
                 15        0.306304
                 34        0.290540
                 61        0.275233
MLB              111       0.257223
                 171       0.236977
                 194       0.228500
                 206       0.222049
                 213       0.219846
NT               4         0.343814
                 7         0.314141
                 9         0.312633
                 14        0.306897
                 31        0.293273
OLB              3         0.374291
                 29        0.294968
                 46        0.282247
                 70        0.270597
                 84        0.267035
SS               135       0.250644
                 274       0.203343
                 341       0.171365
                 344       0.170377
                 345       0.169457

In [183]:
attention_drawn_frame = assignment_data.groupby(["nflId_pr","possession_id", "frame_id", "week"]).agg({"prob_assigned": "sum"}).reset_index()

In [187]:
max_attention_drawn_possession = attention_drawn_frame.groupby(["nflId_pr","possession_id", "week"]).agg({"prob_assigned": "max"}).reset_index()

In [189]:
attention_df = max_attention_drawn_possession.groupby(["nflId_pr"]).agg(num_snaps = ("prob_assigned", len), avg_peak_attention = ("prob_assigned", np.mean)).reset_index().merge(player_data, left_on = "nflId_pr", right_on = "nflId")[["nflId_pr", "officialPosition", "displayName", "num_snaps", "avg_peak_attention"]]

In [168]:
attention_df.rename(mapper = {"displayName":"rusher_name"}, inplace = True, axis = 1)

                               nflId_pr officialPosition       rusher_name  \
officialPosition nflId_pr
DE               35449.0  6     35449.0               DE      Tyson Alualu
                 33131.0  0     33131.0               DE   Calais Campbell
                 38556.0  31    38556.0               DE  Whitney Mercilus
                 46197.0  250   46197.0               DE  Kentavius Street
                 46146.0  240   46146.0               DE       Sam Hubbard
DT               44877.0  189   44877.0               DT    Larry Ogunjobi
                 41239.0  57    41239.0               DT      Aaron Donald
                 42349.0  82    42349.0               DT  Leonard Williams
                 37104.0  20    37104.0               DT   Cameron Heyward
                 46082.0  219   46082.0               DT       Daron Payne
NT               46081.0  218   46081.0               NT          Vita Vea
OLB              44842.0  179   44842.0              OLB         T.J. Watt
                 37145.0  21    37145.0              OLB    Justin Houston
                 38548.0  28    38548.0              OLB     Melvin Ingram
                 41915.0  75    41915.0              OLB   Shaquil Barrett
                 38551.0  29    38551.0              OLB    Chandler Jones

                               num_snaps  avg_peak_attention
officialPosition nflId_pr
DE               35449.0  6           34            1.880706
                 33131.0  0           42            1.866728
                 38556.0  31          30            1.830223
                 46197.0  250         32            1.752314
                 46146.0  240         40            1.729786
DT               44877.0  189         35            1.945568
                 41239.0  57          38            1.763972
                 42349.0  82          30            1.748647
                 37104.0  20          36            1.708590
                 46082.0  219         36            1.674618
NT               46081.0  218         36            1.684346
OLB              44842.0  179         45            1.531772
                 37145.0  21          35            1.511822
                 38548.0  28          31            1.490568
                 41915.0  75          37            1.438348
                 38551.0  29          31            1.379329

In [186]:
attention_drawn_frame.head()

   nflId_pr  possession_id  frame_id  week  prob_assigned
0   33131.0             60         1     7       1.559417
1   33131.0             60         2     7       1.963836
2   33131.0             60         3     7       1.751764
3   33131.0             60         4     7       1.859089
4   33131.0             60         5     7       1.799199

In [188]:
max_attention_drawn_possession

       nflId_pr  possession_id  week  prob_assigned
0       33131.0             60     7       5.808673
1       33131.0             61     7       1.779355
2       33131.0             62     7       1.496604
3       33131.0             63     7       2.370249
4       33131.0             66     7       1.522360
...         ...            ...   ...            ...
36355   53991.0            700     5       1.489587
36356   53991.0            707     5       2.191667
36357   53991.0            713     5       2.073756
36358   53999.0            930     4       1.580820
36359   53999.0            931     4       1.685655

[36360 rows x 4 columns]

In [192]:
attention_df.sort_values(["officialPosition", "num_snaps", "avg_peak_attention"], ascending = [False, False, False])

     nflId_pr officialPosition      displayName  num_snaps  avg_peak_attention
540   52478.0               SS    Brandon Jones         34            1.299684
242   44818.0               SS      Jamal Adams         30            1.419742
1     34465.0               SS  Malcolm Jenkins         25            1.356455
291   44999.0               SS      Chuck Clark         22            1.436737
251   44837.0               SS  Jabrill Peppers         20            1.457992
..        ...              ...              ...        ...                 ...
387   46329.0               CB    Danny Johnson          1            0.672460
166   43299.0               CB        Eli Apple          1            0.583805
351   46168.0               CB     Isaac Yiadom          1            0.494412
534   52469.0               CB  Kristian Fulton          1            0.416450
628   53462.0               CB   Tyson Campbell          1            0.017104

[698 rows x 5 columns]

In [196]:
attention_df.groupby("officialPosition").apply(lambda x: x[x.num_snaps >= 150].sort_values("avg_peak_attention", ascending = False).head(5))

                      nflId_pr officialPosition         displayName  \
officialPosition
DE               308   45274.0               DE         Adam Butler
                 0     33131.0               DE     Calais Campbell
                 426   47800.0               DE     Dexter Lawrence
                 369   46214.0               DE       Bilal Nichols
                 296   45009.0               DE  Al-Quadin Muhammad
DT               515   52415.0               DT       Derrick Brown
                 34    38542.0               DT        Fletcher Cox
                 427   47802.0               DT     Jeffery Simmons
                 144   42480.0               DT       Grady Jarrett
                 114   42349.0               DT    Leonard Williams
NT               213   43455.0               NT         D.J. Reader
                 381   46264.0               NT    Sebastian Joseph
                 394   46487.0               NT          Poona Ford
                 318   46081.0               NT            Vita Vea
                 171   43316.0               NT         Kenny Clark
OLB              210   43435.0              OLB          Matt Judon
                 37    38551.0              OLB      Chandler Jones
                 626   53460.0              OLB          Odafe Oweh
                 131   42401.0              OLB       Markus Golden
                 634   53479.0              OLB       Azeez Ojulari

                      num_snaps  avg_peak_attention
officialPosition
DE               308        193            1.947270
                 0          193            1.929237
                 426        174            1.921718
                 369        153            1.912365
                 296        178            1.848598
DT               515        159            1.962267
                 34         178            1.934513
                 427        268            1.934386
                 144        185            1.910049
                 114        245            1.909682
NT               213        163            1.970517
                 381        185            1.924104
                 394        161            1.824465
                 318        196            1.800666
                 171        238            1.782877
OLB              210        189            1.660065
                 37         163            1.619942
                 626        172            1.611050
                 131        179            1.608108
                 634        166            1.588905